name: SaneEconomy
author: AppleDash
main: org.appledash.saneeconomy.SaneEconomy
version: 0.8.4
loadbefore: [Vault]
commands:
  balance:
    aliases: [bal, money]
    description: Get the balance of yourself or another player.
    usage: /<command> [player name]
    permission: saneeconomy.balance
  ecoadmin:
    aliases: [eco]
    description: Edit players' balances.
    usage: /<command> <give/take/set> <player name> <amount>
    permission: saneeconomy.ecoadmin
  pay:
    aliases: [transfer]
    description: Give some of your money to another player.
    usage: /<command> <player> <amount>
    permission: saneeconomy.pay
  saneeconomy:
    aliases: [saneeco]
    description: Various administrative commands for SaneEconomy.
    usage: /<command> reload-database
    permission: saneeconomy.admin
  balancetop:
    aliases: [baltop, topbal]
    description: Show the players who have the most money on the server.
    usage: /<command>
    permission: saneeconomy.balancetop

permissions:
  saneeconomy.balance:
    description: Allows you to check your balance.
    default: true
  saneeconomy.balance.other:
    description: Allows you to check other players' balances.
    default: op
  saneeconomy.ecoadmin:
    description: Allows you to edit players' balances.
    default: op
  saneeconomy.pay:
    description: Allows you to pay money to other players.
    default: true
  saneeconomy.admin:
    description: Allows you to administrate the plugin.
    default: op
  saneeconomy.balancetop:
    description: Allows you to view the players on the server who have the most money.
    default: true
  saneeconomy.update-notify:
    description: Allows you to be notified of updates to the plugin on join.
    default: op
  saneeconomy.*:
    children:
      saneeconomy.balance: true
      saneeconomy.balance.other: true
      saneeconomy.ecoadmin: true
      saneeconomy.pay: true
      saneeconomy.admin: true
      saneeconomy.balancetop: true
      saneeconomy.update-notify: true
    default: op
